#!/bin/bash
# Title: Top Probed SSIDs
# Description: Examines the recon.db file and pulls the top probed SSIDs ranking them in the process.
#              A probe is not counted towards the tally if it was generated by a device that previously generated the same probe.
#              Single probe requests are not counted or listed in the output.
# Author: Skinny
# Version: 1.0

INFOPATH="/root/loot/info"
RECONDB="/root/recon/recon.db"

# if info loot folder does not exist, then create it
LOG "Creating the Info Loot Directory if it doesn't exist."
if [ ! -d "$INFOPATH" ]; then
  mkdir -p "$INFOPATH"
  LOG "Find your file in the newly created $INFOPATH."
else
  LOG "$INFOPATH exists already."
fi

# Prompts user for filename to dump SSID rank. Default value includes data and time.
FILENAME="$(TEXT_PICKER "Enter a File Name." "TopSSIDs_$(date +%Y%m%d_%H%M%S).txt")"

LOG " "

#SQL Query to find rows in the ssid table that have no BSSID but does have an SSID. Count that row only if it is distinct.

SQL="
SELECT
    COUNT(DISTINCT wd.mac) AS probe_count,
    CASE
        WHEN s.ssid IS NULL OR s.ssid = '' THEN '<HIDDEN>'
        ELSE s.ssid
    END AS ssid_name
FROM
    ssid s
    LEFT JOIN wifi_device wd ON s.wifi_device = wd.hash
WHERE
    s.bssid IS NULL
    AND LENGTH(s.ssid) > 0
GROUP BY
    s.ssid
HAVING
    COUNT(DISTINCT wd.mac) > 1
ORDER BY
    probe_count DESC,
    ssid_name ASC;
"

sqlite3 -separator '|' "$RECONDB" "$SQL" > "$INFOPATH/$FILENAME"

printf "\n" >> "$INFOPATH/$FILENAME"

#Store and Print the Top 10
WINNERS=$(head -n 10 $INFOPATH/$FILENAME)
LOG "The Top 10"
ALERT "--== ToP 10 ==--\n$WINNERS"

LOG " "
LOG "OPERATION COMPLETE."
LOG "To see the full results go to $INFOPATH/$FILENAME"
